### ISSUE TITLE
error when running application: Error [ERR_HTTP_HEADERS_SENT] (on Windows10)

### ISSUE THREAD

**Issue by frunjik** [totaljs/openplatform-application#10]
- git clone https://github.com/totaljs/openplatform-application.git
- cd openplatform-application 
- npm i 
- node index.js
- use app for a bit (click some buttons)

```
ERROR ======= 2024-03-21 23:59:34: Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Gzip.cb (C:\Users\Jeroen\Projects\web\totaljs\apps\openplatform-application\node_modules\total5\controller.js:353:15)
    at Gzip.zlibBufferOnEnd (node:zlib:161:10)
    at Gzip.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Gzip.cb (C:\Users\Jeroen\Projects\web\totaljs\apps\openplatform-application\node_modules\total5\controller.js:353:15)
    at Gzip.zlibBufferOnEnd (node:zlib:161:10)
    at Gzip.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```
Windows 10

Im not sure when it happens (it seems to be timing related)
But happens regurlarly (and I think i have seen it with other total5 apps)

**Comment by petersirka** [comment]
I tested it on Windows 11 and it works without any problem. Can you test it again? But update Total.js framework:

- `npm install total5@beta` and check if `package.json` contains this version `0.0.1-48`

**Comment by frunjik** [comment]
```npm install total5@beta```

seems to fix it - i cannot reproduce the bug after ...
